language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO='django>=1.8,<1.9'

install:
  - make install
  - pip install $DJANGO

script:
    make test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - ymy1019@gmail.com
